# Generated by Django 5.2.1 on 2025-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('CL', 'Clothing'), ('BK', 'Books'), ('TY', 'Toys')], default='EL', max_length=2),
        ),
    ]
